name: Deploy Anki Bot

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted  

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python Virtual Environment
        run: |
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi

      - name: Install dependencies
        run: |
          ./venv/bin/pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            ./venv/bin/pip install -r requirements.txt
          fi

      - name: Restart Systemd Service
        run: |
          sudo systemctl restart ankibot.service